version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  vote:
    build: ./vote
    ports:
      - "5000:80"
    environment:
      OPTION_A: "Cats"
      OPTION_B: "Dogs"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  db-data:
