version: "2"
authtoken: 32rnua6V7k2rriSIrgz1NUk9FTC_2Cbpmk6kNgMez4Mu9ugu9
tunnels:
  webhook:
    addr: 5000
    proto: http
    host_header: "localhost:5000"

  jenkins:
    addr: 8080
    proto: http
    host_header: "localhost:8080"
