name: Voting App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fix Folder Permissions
        run: |
          chmod -R 777 result vote worker || true

      - name: Install Dependencies (Result App)
        run: |
          cd result
          npm install

      - name: Run Tests
        run: |
          cd result
          npm test || echo "No tests defined, skipping..."

      - name: SonarQube Scan
        run: |
          docker run --rm \
            --network host \
            -e SONAR_HOST_URL="http://127.0.0.1:9000" \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v $(pwd)/result:/usr/src:Z \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=voting-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://127.0.0.1:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarQube Quality Gate
        run: |
          echo "Waiting for SonarQube Quality Gate..."
          STATUS=""
          while [ "$STATUS" != "OK" ] && [ "$STATUS" != "FAILED" ]; do
            sleep 5
            STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
              "http://127.0.0.1:9000/api/qualitygates/project_status?projectKey=voting-app" \
              | jq -r '.projectStatus.status')
            echo "Current status: $STATUS"
          done
          if [ "$STATUS" != "OK" ]; then
            echo "❌ SonarQube Quality Gate failed!"
            exit 1
          fi
          echo "✅ Quality Gate passed! Continuing pipeline..."

      - name: Build Docker Images
        run: |
          docker build -t 31793179/voting-app-vote:latest ./vote
          docker build -t 31793179/voting-app-result:latest ./result
          docker build -t 31793179/voting-app-worker:latest ./worker

      - name: Generate Trivy HTML Reports
        run: |
          python3 generate_trivy_report.py

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push 31793179/voting-app-vote:latest
          docker push 31793179/voting-app-result:latest
          docker push 31793179/voting-app-worker:latest
